export const getElo = (rating) => {
    if (rating >= 2501) return { name: 'Lenda', class: 'elo-legend', icon: '🐉' };
    if (rating >= 2301) return { name: 'Radiante', class: 'elo-radiant', icon: '✨' };
    if (rating >= 2101) return { name: 'Challenger', class: 'elo-challenger', icon: '🏆' };
    if (rating >= 1901) return { name: 'Grão-Mestre', class: 'elo-grandmaster', icon: '🔴' };
    if (rating >= 1751) return { name: 'Mestre', class: 'elo-master', icon: '👑' };
    if (rating >= 1651) return { name: 'Safira', class: 'elo-sapphire', icon: '🔹' };
    if (rating >= 1551) return { name: 'Rubi', class: 'elo-ruby', icon: '🔻' };
    if (rating >= 1451) return { name: 'Diamante', class: 'elo-diamond', icon: '💎' };
    if (rating >= 1351) return { name: 'Esmeralda', class: 'elo-emerald', icon: '✳️' };
    if (rating >= 1251) return { name: 'Platina', class: 'elo-platinum', icon: '💠' };
    if (rating >= 1151) return { name: 'Ouro', class: 'elo-gold', icon: '🥇' };
    if (rating >= 1051) return { name: 'Prata', class: 'elo-silver', icon: '🥈' };
    if (rating >= 951) return { name: 'Bronze', class: 'elo-bronze', icon: '🥉' };
    if (rating >= 851) return { name: 'Ferro', class: 'elo-iron', icon: '⚙️' };
    if (rating >= 751) return { name: 'Cobre', class: 'elo-copper', icon: '🟫' };
    if (rating >= 600) return { name: 'Pedra', class: 'elo-stone', icon: '🪨' };
    if (rating >= 400) return { name: 'Madeira', class: 'elo-wood', icon: '🪵' };
    if (rating >= 200) return { name: 'Papelão', class: 'elo-cardboard', icon: '📦' };
    return { name: 'Plástico', class: 'elo-plastic', icon: '🥤' };
};
